name: RDP Windows Via CRD

on:
  workflow_dispatch:
    inputs:
      gh_crd_auth:
        description: "Auth Code CRD (from remotedesktop.google.com/headless)"
        required: true
      gh_pc_name:
        description: "PC Name (displayed in CRD)"
        required: true
      gh_pin_crd:
        description: "PIN (min 6 digits)"
        required: true
      runtime_minutes:
        description: "Runtime in minutes (max 360; default 355)"
        default: "355"

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

env:
  RDP_USER: mycrd
  RDP_PASS: MySecurePass123

jobs:
  crd:
    runs-on: windows-2022
    timeout-minutes: 370
    steps:
      - name: 🔧 Resolve inputs
        id: cfg
        run: |
          function ToIntOr($v, $def){ if("$v" -match '^\d+$'){[int]$v}else{[int]$def} }

          $runtime = ToIntOr "${{ inputs.runtime_minutes }}" 355
          if ($runtime -gt 360) { $runtime = 355 }
          if ($runtime -lt 6) { $runtime = 355 }

          "code=${{ inputs.gh_crd_auth }}"   | Out-File -Append $env:GITHUB_OUTPUT
          "pcname=${{ inputs.gh_pc_name }}"  | Out-File -Append $env:GITHUB_OUTPUT
          "pin=${{ inputs.gh_pin_crd }}"     | Out-File -Append $env:GITHUB_OUTPUT
          "runtime=$runtime"                 | Out-File -Append $env:GITHUB_OUTPUT
          Write-Host "Resolved runtime=$runtime"

      - name: 🔐 Enable RDP user (optional, for local access)
        run: |
          $u="${{ env.RDP_USER }}"; $p="${{ env.RDP_PASS }}"
